# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HxAl1Ejf5uAG3ZWah5Ez1YECbAHS9QWp
"""

# -*- coding: utf-8 -*-
""" Code for Assingment-1 
Automatic generation  in Colaboratory.
Original file at
    https://colab.research.google.com/drive/1HxAl1Ejf5uAG3ZWah5Ez1YECbAHS9QWp#scrollTo=4NbJMCzXyRJB
"""
import random
#let us repeat the experiment for 10000 times
n_simulations=10000
count = 0

def det_of_matrix():
    global count
    for i in range (n_simulations):
#Let a,b,c,d are the entries of the matrix in the respective order with entries either 0 or 1.       
        a=random.randint(0,1)
        b=random.randint(0,1)
        c=random.randint(0,1)
        d=random.randint(0,1)
#Increase the count by one when the determinant is positive.        
        if a == 1 and d == 1 and b == 1:
            count += 1
            
        if a == 1 and d == 1 and b == 0 and c == 1:
            count += 1

print('The probability of getting a matrix with positive determinant is :')
det_of_matrix()
str1 = count/n_simulations
print(str1)

print('The theriotical probability of getting a matrix with positive determinant is 0.1875 ')
#Thus we can say that the experimental value is much close to the theoritical value.