# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fCWGa3mJKNtk8fQcJokEcAldycwmzpKk
"""

# -*- coding: utf-8 -*-
""" Code for Assingment-1 
Automatic generation  in Colaboratory.
Original file at
    https://colab.research.google.com/drive/1fCWGa3mJKNtk8fQcJokEcAldycwmzpKk?authuser=3
"""
import random 
total1 = 0
total2 = 0
#a,b,c,d are the elements of the matrix in the respective order

for i in range(10000):
    
    a = random.randint(0,1)
    b = random.randint(0,1)
    c = random.randint(0,1)
    d = random.randint(0,1)
#for the determinant to be positive with the given entries both a and d should be 1 and atleast one among b and c should be 0
#total1 is the case where b=0 and total2 be the case where c=0 and b=1   
    if a == 1 and d == 1 and b == 0:
        total1 += 1 
    if a == 1 and d == 1 and c == 0 and b == 1:
        total2 += 1
        
total = (total1 + total2)
Total_float = total/10000.00
formatted_float = "{:.4f}".format(Total_float)
print("The probaboility of the determinant being positive is :")
print(formatted_float)
print("The theoritical probability for the determinant being positive is 0.1875")
#Thus we can say that practical and the theoritical probabilities are very close with a minute error